swagger: '2.0'
info:
  version: 1.0.0
  title: NIH Endotypes API
  description: NIH Endotypes API
  termsOfService: None
  contact:
    name: Hong Yi
    url: 'https://github.com/renci/nih-endotypes-api'
    email: hongyi@renci.org
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
host: 'localhost:5000'
basePath: /v1
schemes:
  - https
paths:
  /endotypes:
    get:
      summary: list of endotypes
      description: list of endotypes
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            properties:
              dateOfBirth:
                type: string
              race:
                type: string
              sex:
                type: string
              visit:
                type: array
                items:
                  $ref: '#/definitions/visit'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                endotypeID:
                  type: string
                endotypeDescription:
                  type: string
                periods:
                  type: array
                  items:
                    type: object
                    properties:
                      startTime:
                        type: string
                        format: date-time
                      endTime:
                        type: string
                        format: date-time
        '400':
          description: Invalid parameter
        '404':
          description: No endotypes found
        '500':
          description: Server error
definitions:
  exposure:
    type: array
    items:
      type: object
      properties:
        value:
          type: string
        units:
          type: string
        exposureType:
          type: string
        timeWindow:
          type: string
  visit:
    type: object
    properties:
      time:
        type: string
      zip:
        type: string
      visitType:
        type: string
      icdCode:
        type: string
      exposures:
        $ref: '#/definitions/exposure'
