# coding: utf-8

from __future__ import absolute_import
from models.base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from util import deserialize_model

class EndotypesPeriod(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, start_time: str=None, end_time: str=None):
        """
        EndotypesPeriod - a model defined in Swagger

        :param start_time: The start_time of this EndotypesPeriod.
        :type start_time: str
        :param end_time: The end_time of this EndotypesPeriod.
        :type end_time: str
        """
        self.swagger_types = {
            'start_time': str,
            'end_time': str
        }

        self.attribute_map = {
            'start_time': 'start_time',
            'end_time': 'end_time'
        }

        self._start_time = start_time
        self._end_time = end_time

    @classmethod
    def from_dict(cls, dikt) -> 'EndotypesPeriod':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The endotypes_period of this EndotypesPeriod.
        :rtype: EndotypesPeriod
        """
        return deserialize_model(dikt, cls)

    @property
    def start_time(self) -> str:
        """
        Gets the start_time of this EndotypesPeriod.

        :return: The start_time of this EndotypesPeriod.
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: str):
        """
        Sets the start_time of this EndotypesPeriod.

        :param start_time: The start_time of this EndotypesPeriod.
        :type start_time: str
        """

        self._start_time = start_time

    @property
    def end_time(self) -> str:
        """
        Gets the end_time of this EndotypesPeriod.

        :return: The end_time of this EndotypesPeriod.
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time: str):
        """
        Sets the end_time of this EndotypesPeriod.

        :param end_time: The end_time of this EndotypesPeriod.
        :type end_time: str
        """

        self._end_time = end_time

