# coding: utf-8

from __future__ import absolute_import
from models.endotypes_periods import EndotypesPeriods
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from util import deserialize_model


class InlineResponse200(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, endotype_id: str=None, endotype_description: str=None, periods: List[EndotypesPeriods]=None):
        """
        InlineResponse200 - a model defined in Swagger

        :param endotype_id: The endotype_id of this InlineResponse200.
        :type endotype_id: str
        :param endotype_description: The endotype_description of this InlineResponse200.
        :type endotype_description: str
        :param periods: The periods of this InlineResponse200.
        :type periods: List[EndotypesPeriods]
        """
        self.swagger_types = {
            'endotype_id': str,
            'endotype_description': str,
            'periods': List[EndotypesPeriods]
        }

        self.attribute_map = {
            'endotype_id': 'endotypeID',
            'endotype_description': 'endotypeDescription',
            'periods': 'periods'
        }

        self._endotype_id = endotype_id
        self._endotype_description = endotype_description
        self._periods = periods

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.
        :rtype: InlineResponse200
        """
        return deserialize_model(dikt, cls)

    @property
    def endotype_id(self) -> str:
        """
        Gets the endotype_id of this InlineResponse200.

        :return: The endotype_id of this InlineResponse200.
        :rtype: str
        """
        return self._endotype_id

    @endotype_id.setter
    def endotype_id(self, endotype_id: str):
        """
        Sets the endotype_id of this InlineResponse200.

        :param endotype_id: The endotype_id of this InlineResponse200.
        :type endotype_id: str
        """

        self._endotype_id = endotype_id

    @property
    def endotype_description(self) -> str:
        """
        Gets the endotype_description of this InlineResponse200.

        :return: The endotype_description of this InlineResponse200.
        :rtype: str
        """
        return self._endotype_description

    @endotype_description.setter
    def endotype_description(self, endotype_description: str):
        """
        Sets the endotype_description of this InlineResponse200.

        :param endotype_description: The endotype_description of this InlineResponse200.
        :type endotype_description: str
        """

        self._endotype_description = endotype_description

    @property
    def periods(self) -> List[EndotypesPeriods]:
        """
        Gets the periods of this InlineResponse200.

        :return: The periods of this InlineResponse200.
        :rtype: List[EndotypesPeriods]
        """
        return self._periods

    @periods.setter
    def periods(self, periods: List[EndotypesPeriods]):
        """
        Sets the periods of this InlineResponse200.

        :param periods: The periods of this InlineResponse200.
        :type periods: List[EndotypesPeriods]
        """

        self._periods = periods

