# coding: utf-8

from __future__ import absolute_import
from models.response200_output import Response200Output
from models.base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from util import deserialize_model

class Response200(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, output: List[Response200Output]=None):
        """
        Response200 - a model defined in Swagger

        :param output: The output of this Response200.
        :type output: List[Response200Output]
        """
        self.swagger_types = {
            'output': List[Response200Output]
        }

        self.attribute_map = {
            'output': 'output'
        }

        self._output = output

    @classmethod
    def from_dict(cls, dikt) -> 'Response200':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The response_200 of this Response200.
        :rtype: Response200
        """
        return deserialize_model(dikt, cls)

    @property
    def output(self) -> List[Response200Output]:
        """
        Gets the output of this Response200.

        :return: The output of this Response200.
        :rtype: List[Response200Output]
        """
        return self._output

    @output.setter
    def output(self, output: List[Response200Output]):
        """
        Sets the output of this Response200.

        :param output: The output of this Response200.
        :type output: List[Response200Output]
        """

        self._output = output

