---
swagger: "2.0"
info:
  description: "NIH Endotypes API - Refer to <a href=\"https://docs.google.com/document/d/1gtkYf6ITfexxEQj9WYPW8iqskT-tZh84LnhtLTmboAA/edit\">User Manual</a> on how to use the API."
  version: "1.0.0"
  title: "NIH Endotypes API"
  termsOfService: "None"
  contact:
    name: "Hong Yi"
    url: "https://github.com/renci/nih-endotypes-api"
    email: "hongyi@renci.org"
  license:
    name: "MIT"
    url: "http://opensource.org/licenses/MIT"
host: "localhost:7000"
basePath: "/v1"
schemes:
- "https"
paths:
  /endotypes:
    post:
      summary: "Get list of endotypes based on input"
      description: "Get list of endotypes based on input"
      operationId: "endotypes_get"
      produces:
        - "application/json"
      consumes:
        - "application/json"
      parameters:
        - in: "body"
          name: "input"
          required: true
          schema:
            $ref: "#/definitions/input"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/inline_response_200"
        400:
          description: "Invalid parameter"
        404:
          description: "No endotypes found"
        500:
          description: "Server error"
      x-swagger-router-controller: "controllers.default_controller"
definitions:
  exposure:
    properties:
      value:
        type: "string"
      units:
        type: "string"
      exposure_type:
        type: "string"
  visit:
    properties:
      time:
        type: "string"
        format: "date-time"
      lat:
        type: "number"
        format: "float"
      lon:
        type: "number"
        format: "float"
      visit_type:
        type: "string"
        pattern: "^(INPATIENT|OUTPATIENT|EMERGENCY|inpatient|outpatient|emergency)$"
      icd_codes:
        type: "string"
      exposure:
        $ref: "#/definitions/exposure"
  input:
    properties:
      date_of_birth:
        type: "string"
        format: "date"
      race:
        type: "string"
      sex:
        type: "string"
        pattern: "^(F|M|Female|Male|FEMALE|MALE)$"
      model_type:
        type: "string"
        pattern: "^[M|m][0-9]$"
      visits:
        type: "array"
        items:
          $ref: "#/definitions/visit"
  endotypes_period:
    properties:
      start_time:
        type: "string"
        format: "date-time"
      end_time:
        type: "string"
        format: "date-time"
  inline_response_200:
    properties:
      endotype_id:
        type: "string"
      endotype_description:
        type: "string"
      endotype_evidence:
        type: "string"
      periods:
        type: "array"
        items:
          $ref: "#/definitions/endotypes_period"
