---
swagger: "2.0"
info:
  description: "NIH Endotypes API - Refer to <a href=\\\"https://docs.google.com/document/d/1gtkYf6ITfexxEQj9WYPW8iqskT-tZh84LnhtLTmboAA/edit\\\
    \">User Manual</a> on how to use the API."
  version: "1.0.0"
  title: "NIH Endotypes API"
  termsOfService: "None"
  contact:
    name: "Hong Yi"
    url: "https://github.com/renci/nih-endotypes-api"
    email: "hongyi@renci.org"
  license:
    name: "MIT"
    url: "http://opensource.org/licenses/MIT"
host: "endotypes.renci.org"
basePath: "/v1"
schemes:
- "https"
paths:
  /endotypes:
    post:
      summary: "Get list of endotypes based on input as a POST request"
      description: "list of endotypes based on input\n@input\n- JSON object with required\
        \ input\n\n@return\n- JSON object that returns array of predicted endotypes\n"
      operationId: "endotypes_post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "input"
        required: true
        schema:
          $ref: "#/definitions/input"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/response_200"
        400:
          description: "Invalid parameter"
        404:
          description: "No endotypes found"
        500:
          description: "Server error"
      x-swagger-router-controller: "controllers.default_controller"
definitions:
  exposure:
    type: "object"
    additionalProperties: True
    properties:
      value:
        type: "number"
        format: "float"
        example: 33.3
      units:
        type: "string"
        example: "ugm3"
      exposure_type:
        type: "string"
        example: "pm25"
  visit:
    type: "object"
    additionalProperties: true
    properties:
      time:
        type: "string"
        example: "2017-10-12T21:12:29.451Z"
      lat:
        type: "string"
        example: "20"
      lon:
        type: "string"
        example: "20"
      visit_type:
        type: "string"
        example: "INPATIENT"
        pattern: "^(INPATIENT|OUTPATIENT|EMERGENCY|inpatient|outpatient|emergency)$"
        x-regex: "^(INPATIENT|OUTPATIENT|EMERGENCY|inpatient|outpatient|emergency)$"
        x-modifiers: []
      icd_codes:
        type: "string"
        example: "ICD9:V12,ICD9:E002"
        description: "comma-separated standard ICD-9 or ICD-10 codes associated with\
          \ the visit"
      exposure:
        $ref: "#/definitions/exposure"
  input:
    type: "object"
    additionalProperties: true
    properties:
      date_of_birth:
        type: "string"
        example: '2017-10-04'
      race:
        type: "string"
        example: "1"
        description: "race code ranged from 1 to 6 with the following mapping:\n1:\
          \ WHITE OR CAUCASIAN\n2: BLACK OR AFRICAN AMERICAN\n3: AMERICAN INDIAN OR\
          \ ALASKA NATIVE\n4: ASIAN\n5: NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER\n\
          6: OTHER/HISPANIC\n"
      sex:
        type: "string"
        example: "M"
        pattern: "^(F|M|f|m)$"
        x-regex: "^(F|M|f|m)$"
        x-modifiers: []
      model_type:
        type: "string"
        example: "M0"
        pattern: "^[M|m][0-9]$"
        x-regex: "^[M|m][0-9]$"
        x-modifiers: []
      visits:
        type: "array"
        items:
          $ref: "#/definitions/visit"
  endotypes_period:
    type: "object"
    additionalProperties: True
    properties:
      start_time:
        type: "string"
      end_time:
        type: "string"
  response_200:
    type: "object"
    properties:
      output:
        type: array
        items:
            type: object
            properties:
              endotype_id:
                type: "string"
              endotype_description:
                type: "string"
              endotype_evidence:
                type: "string"
              periods:
                type: "array"
                items:
                  $ref: "#/definitions/endotypes_period"
